In [1]:
import os
import json
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")
%matplotlib inline

In [2]:
random.seed(42)

In [3]:
file_path = "VQA_RAD/train.json"
train_data = pd.read_json(file_path)
train_data.head()

,qid,phrase_type,qid_linked_id,image_case_url,image_name,image_organ,evaluation,question,question_rephrase,question_relation,question_frame,question_type,answer,answer_type
0,474,test_freeform,232f0622-17ed-4c95-8b2f-df2956805d9b,https://medpix.nlm.nih.gov/case?id=0cf531c9-62...,synpic19118.jpg,CHEST,not evaluated,What is this lucency amid densities in the rig...,NULL,NULL,NULL,PRES,The right bronchus,OPEN
1,478,freeform,36add8a1-198b-4bb5-a852-33862c6c2eed,https://medpix.nlm.nih.gov/case?id=0cf531c9-62...,synpic19118.jpg,CHEST,not evaluated,Are these small opacities in the right lung ca...,NULL,NULL,NULL,PRES,No,CLOSED
2,509,freeform,8fb87a29-4d26-48a0-80f6-5d83f520e97d,https://medpix.nlm.nih.gov/case?id=0cf531c9-62...,synpic19118.jpg,CHEST,not evaluated,Is this a cyst in the left lung?,NULL,NULL,NULL,POS,No,CLOSED
3,468,test_freeform,1265fa38-5d6e-4177-aec6-f1e3844d2e87,https://medpix.nlm.nih.gov/case?id=7b09f576-8f...,synpic24319.jpg,ABD,not evaluated,Is the liver visible in the image?,NULL,NULL,NULL,PRES,No,CLOSED
4,489,freeform,54eb6ae0-64ee-4b41-a29a-8d43cf1ce028,https://medpix.nlm.nih.gov/case?id=7b09f576-8f...,synpic24319.jpg,ABD,not evaluated,What are these densities inside the intestines?,NULL,NULL,NULL,PRES,Contrast,OPEN

In [6]:
print(train_data['answer_type'].unique())

['OPEN' 'CLOSED']

In [9]:
closed_ended_train_data = train_data[train_data['answer_type'] == 'CLOSED']
open_ended_train_data = train_data[train_data['answer_type'] == 'OPEN'] 

print(closed_ended_train_data['answer_type'].count())
print(open_ended_train_data['answer_type'].count())

916
662

In [10]:
print(closed_ended_train_data['answer'].unique())

['No' 'no' 'pleural effusion' 'YES' 'Yes' 'yes' 'Diffuse' 'Left' 'MRI'
 'heterogeneous' 'Axial' 'FLAIR' 'Solid' 'Exterior' 'Outside' 'Hypodense'
 'Abnormal' 'Right side' 'Cystic' 'CT' 'With contrast' 'Not sure' 'Maybe'
 'bilateral' 'both sides' 'PA' 'Right' 'Female' 'Asymmetric'
 'non-contrast' 'Smaller' 'contrast' 'Both' 'In the vasculature'
 'Superior' 'Normal' 'Medical process' 'genetic' 'Vascular' 'Left kidney'
 'more dense' 'multilobulated' 'Enlarged' 'Abscess' 'with contrast'
 'Less dense' 'The surrounding tissue' 'Base' 'Hyperinflation'
 'On top of the patient' " superficial to the patient's skin" 'Just one'
 'Irregular' 'Bilateral frontal lobes' 'Non-contrast CT' 'White matter'
 'Gray matter' 'supratentorial' 'Contrast CT with GI and IV contrast'
 'abnormal']

In [11]:
print(open_ended_train_data['answer'][0])

The right bronchus

In [19]:
closed_ended_train_data['answer'] = closed_ended_train_data['answer'].str.lower()
print(closed_ended_train_data['answer'].unique())

['no' 'pleural effusion' 'yes' 'diffuse' 'left' 'mri' 'heterogeneous'
 'axial' 'flair' 'solid' 'exterior' 'outside' 'hypodense' 'abnormal'
 'right side' 'cystic' 'ct' 'with contrast' 'not sure' 'maybe' 'bilateral'
 'both sides' 'pa' 'right' 'female' 'asymmetric' 'non-contrast' 'smaller'
 'contrast' 'both' 'in the vasculature' 'superior' 'normal'
 'medical process' 'genetic' 'vascular' 'left kidney' 'more dense'
 'multilobulated' 'enlarged' 'abscess' 'less dense'
 'the surrounding tissue' 'base' 'hyperinflation' 'on top of the patient'
 " superficial to the patient's skin" 'just one' 'irregular'
 'bilateral frontal lobes' 'non-contrast ct' 'white matter' 'gray matter'
 'supratentorial' 'contrast ct with gi and iv contrast']

In [20]:
print(closed_ended_train_data['answer_type'].count())

916

In [22]:
closed_ended_train_data['answer'] = closed_ended_train_data['answer'].str.strip()
print(closed_ended_train_data['answer'].unique())

['no' 'pleural effusion' 'yes' 'diffuse' 'left' 'mri' 'heterogeneous'
 'axial' 'flair' 'solid' 'exterior' 'outside' 'hypodense' 'abnormal'
 'right side' 'cystic' 'ct' 'with contrast' 'not sure' 'maybe' 'bilateral'
 'both sides' 'pa' 'right' 'female' 'asymmetric' 'non-contrast' 'smaller'
 'contrast' 'both' 'in the vasculature' 'superior' 'normal'
 'medical process' 'genetic' 'vascular' 'left kidney' 'more dense'
 'multilobulated' 'enlarged' 'abscess' 'less dense'
 'the surrounding tissue' 'base' 'hyperinflation' 'on top of the patient'
 "superficial to the patient's skin" 'just one' 'irregular'
 'bilateral frontal lobes' 'non-contrast ct' 'white matter' 'gray matter'
 'supratentorial' 'contrast ct with gi and iv contrast']

In [24]:
print(closed_ended_train_data.columns.to_list())

['qid', 'phrase_type', 'qid_linked_id', 'image_case_url', 'image_name', 'image_organ', 'evaluation', 'question', 'question_rephrase', 'question_relation', 'question_frame', 'question_type', 'answer', 'answer_type']

In [27]:
len(train_data.columns)

14

In [28]:
len(closed_ended_train_data.columns)

14

In [29]:
no_ans_data = closed_ended_train_data[closed_ended_train_data['answer'] == 'no']
print(no_ans_data.count())
len(no_ans_data.columns)

qid                  445
phrase_type          445
qid_linked_id        445
image_case_url       445
image_name           445
image_organ          445
evaluation           445
question             445
question_rephrase    445
question_relation    445
question_frame       445
question_type        445
answer               445
answer_type          445
dtype: int64

14

In [30]:
yes_ans_data = closed_ended_train_data[closed_ended_train_data['answer'] == 'yes']
print(yes_ans_data.count())
len(yes_ans_data.columns)

qid                  391
phrase_type          391
qid_linked_id        391
image_case_url       391
image_name           391
image_organ          391
evaluation           391
question             391
question_rephrase    390
question_relation    391
question_frame       391
question_type        391
answer               391
answer_type          391
dtype: int64

14

In [41]:
binary_data = no_ans_data.merge(yes_ans_data, how='outer')
binary_data.head()

,qid,phrase_type,qid_linked_id,image_case_url,image_name,image_organ,evaluation,question,question_rephrase,question_relation,question_frame,question_type,answer,answer_type
0,0,freeform,03f451ca-de62-4617-9679-e836026a7642,https://medpix.nlm.nih.gov/case?id=48e1dd0e-85...,synpic54610.jpg,HEAD,not evaluated,Are regions of the brain infarcted?,NULL,NULL,NULL,PRES,yes,CLOSED
1,1,freeform,06e26b2c-04b9-42bc-8e98-1de30a0f7682,https://medpix.nlm.nih.gov/case?id=b197277b-69...,synpic29265.jpg,CHEST,not evaluated,Are the lungs normal appearing?,NULL,NULL,NULL,ABN,no,CLOSED
2,2,freeform,0d0e8b6b-7753-4788-9b6d-dc7f25250c3f,https://medpix.nlm.nih.gov/case?id=b197277b-69...,synpic29265.jpg,CHEST,not evaluated,Is there evidence of a pneumothorax,NULL,NULL,NULL,PRES,no,CLOSED
3,4,freeform,1179f612-12e0-4dda-aee0-f14a5200be7b,https://medpix.nlm.nih.gov/case?id=b197277b-69...,synpic29265.jpg,CHEST,given,Is this a MRI of the chest?,NULL,NULL,NULL,MODALITY,no,CLOSED
4,6,freeform,27169439-b749-4b2f-8abe-bfb57a46ce53,https://medpix.nlm.nih.gov/case?id=19aa8a2b-35...,synpic28602.jpg,CHEST,not evaluated,Is the trachea midline?,NULL,NULL,NULL,PRES,yes,CLOSED

In [42]:
print(binary_data.count())
print(binary_data['answer'].unique())
len(binary_data.columns)

qid                  836
phrase_type          836
qid_linked_id        836
image_case_url       836
image_name           836
image_organ          836
evaluation           836
question             836
question_rephrase    835
question_relation    836
question_frame       836
question_type        836
answer               836
answer_type          836
dtype: int64
['yes' 'no']

14

In [ ]:
# save binary data as JSON file
with open(os.path.join(VQA_RAD, "binary_train.json"), "w") as f:
    json.dump(binary_data, f, indent=2)